debug:
	LANGUAGE=th NODE_ENV=development bun --inspect=ws://localhost:6499/ai-agent-api src/index.ts

dev:
	LANGUAGE=th NODE_ENV=development PORT=8080 bun run dev

build:
	LANGUAGE=th NODE_ENV=production PORT=8080 bun run build

start:
	LANGUAGE=th NODE_ENV=production PORT=8080 ./dist/server
